- name: NodeX config
  hosts: dockers
  tasks:
    - name: Модификация конфигов
      become: yes
      vars:
        node_directory: /docker/NodeX
        node_prefix: node
        zabbix_config: zabbix_agentd.conf
      block:

        - name: Install python3-docker
          apt:
            update_cache: true
            cache_valid_time: 3600
            pkg:
              - python3-docker

        - name: Создаём Image для Node
          docker_image:
            name: '{{ node_prefix }}'
            source: build
            build:
              path: "{{ node_directory }}"
            state: present

        - name: Запускаем контейнеры с NodeX
          docker_container:
            name: "{{ node_prefix }}{{ item }}"
            image: "{{ node_prefix }}"
            state: started
            ports:
              - "2002{{ item }}:22"
              - "2005{{ item }}:10051"
          loop: "{{ range(2) | list }}"

        - name: Изменение Hostname в конфиге для Zabbix_agent
          community.docker.docker_container_exec:
            container: "{{ node_prefix }}{{ item }}"
            command:
              /bin/bash -c "sed -i 's/Hostname=Zabbix server/Hostname="{{ node_prefix }}{{ item }}"/' /etc/zabbix/zabbix_agentd.conf"
          loop: "{{ range(2) | list }}"

        - name: Перечитаем конфиг Zabbix внутри контейнера
          community.docker.docker_container_exec:
            container: "{{ node_prefix }}{{ item }}"
            command: /usr/sbin/zabbix_agentd -R userparameter_reload
          loop: "{{ range(2) | list }}"
          register: result

        - name: Print stdout
          debug:
            var: result
