- name: NodeX config
  hosts: dockers
  tasks:
    - name: Модификация конфигов
      become: yes
      vars:
        node_directory: /docker/NodeX
        node_prefix: node
        node_count: 2
        zabbix_config: zabbix_agentd.conf
      block:

        - name: Install python3-docker
          apt:
            update_cache: true
            cache_valid_time: 3600
            pkg:
              - python3-docker

        - name: Создаём директорию для сборки
          file:
            path: '{{ node_directory }}'
            state: directory
            owner: root
            group: root
            mode: '0755'

        - name: Копируем Dockerfile + остальные файлы для сборки контейнера...
          copy:
            src: ./service/
            dest: '{{ node_directory }}'
            owner: root
            group: root
            mode: '0644'

        - name: Делаем "entrypoint.sh" исполняемым "+x"
          file: "dest={{ node_directory }}/entrypoint.sh mode=a+x"

        - name: Создаём Image для Node
          docker_image:
            name: '{{ node_prefix }}'
            source: build
            build:
              path: "{{ node_directory }}"
            state: present

        - name: Запускаем контейнеры с NodeX
          docker_container:
            name: "{{ node_prefix }}{{ item }}"
            image: "{{ node_prefix }}"
            hostname: "{{ node_prefix }}{{ item }}"
            memory: 256M
            networks:
              - name: "zabbix-docker_backend"
            state: started
            ports:
              - "2002{{ item }}:22"
              - "2005{{ item }}:10050"
          loop: "{{ range(node_count) | list }}"

        - name: Изменение Hostname в конфиге для Zabbix_agent
          community.docker.docker_container_exec:
            container: "{{ node_prefix }}{{ item }}"
            command:
              /bin/bash -c "sed -i 's/Hostname=Zabbix server/Hostname="{{ node_prefix }}{{ item }}"/' /etc/zabbix/zabbix_agentd.conf"
          loop: "{{ range(node_count) | list }}"

        - name: Перечитаем конфиг Zabbix внутри контейнера
          community.docker.docker_container_exec:
            container: "{{ node_prefix }}{{ item }}"
            command: /bin/bash -c "killall zabbix_agentd; /usr/sbin/zabbix_agentd"
          loop: "{{ range(node_count) | list }}"
          register: result

        - name: Print stdout
          debug:
            var: result
